TEMPORAL_CREATION=(CREATE TABLE temporal(
    artist VARCHAR(50),
    song VARCHAR(100),
    duration_ms int,
    explicit varchar(10),
    year int,
    popularity decimal(10,4),
    danceability decimal(10,4),
    energy decimal(10,4),
    key int, 
    loudness decimal(10,4),
    mode decimal(10,4),
    speechiness decimal(10,4),
    acousticness decimal(10,4),
    instrumentalness decimal(10,7),
    liveness decimal(10,4),
    valence decimal(10,4),
    tempo decimal(10,4),
    genre varchar(50) 
))